노드 조회, 노드 전체 조회 api 구현
boostcampwm-2024/web15-OctoDocs pull request #120
Opened 2024-11-12 12:38 UTC by ezcolin2

## 🔖 연관된 이슈

- #110 

## 📂 작업 내용

- id로 노드 하나 조회 API 구현
- 모든 노드 조회 API 구현

노드를 조회할 때는 페이지의 content는 가져오지 않고 id와 title만 가져오도록 구현했습니다.

2024-11-12 13:38 UTC, Tolerblanc requested changes

2024-11-12 13:38 UTC, Tolerblanc commented on backend/src/node/node.service.ts
> +        'outgoingEdges.id',
P3: 아마 `repository.select` 랑 `relations` 옵션으로 간단하게 가져올 수 있는 걸로 알고있는데, 쿼리 빌더를 쓰신 이유가 있을까요?

2024-11-13 01:24 UTC, ezcolin2 commented on backend/src/node/node.service.ts
> +        'outgoingEdges.id',
![image](https://github.com/user-attachments/assets/0391bf1d-fe9d-4063-9f3f-6ef25154205b)
node와 연결된 page 정보는 content를 제외하고 달라는 요청이 있었어요.
그래서 page.content를 제외해야 하는데 select에 직접 page.id, page.title을 지정하면 해당 key가 없다고 오류가 나더라고요
그래서 query builder를 사용해서 연관된 엔티티의 원하는 컬럼만 가져올 수 있게 구현했습니다!

2024-11-13 01:27 UTC, summersummerwhy approved these changes

2024-11-13 01:27 UTC, summersummerwhy commented on backend/src/node/node.service.ts
> +      .leftJoinAndSelect('node.incomingEdges', 'incomingEdges')
코드로 보니까 생각보다 join operation이 많네요... outgoingEdges랑 incomingEdges 부분이 DB에서 꼭 필요한지 후에 검토가 필요할 것 같아요

2024-11-13 01:27 UTC, summersummerwhy commented on backend/src/node/node.service.ts
> +        'node.x',
출발하거나 도착하는 엣지들의 id를 통째로 가져오는거죠? 특정 노드에서 출발/도착하는 edge를 가져오는 작업은 차라리 edge service가 하는게 낫..지 않을까요? 일단 엣지 api를 써보고 결정해야겠네요

2024-11-13 01:36 UTC, ezcolin2 commented on backend/src/node/node.service.ts
> +      .leftJoinAndSelect('node.incomingEdges', 'incomingEdges')
edge가 굉장히 많아진다면 join 할 때 성능 상 문제가 되긴 하겠네요

2024-11-13 01:37 UTC, ezcolin2 commented on backend/src/node/node.service.ts
> +        'node.x',
네 다시 생각해보니 node와 edge를 가져와서 표현할 때 따로 가져오는 편이 나을 것 같아요.
node에서 한 번에 가져온 다음 incoming, outgoing edges를 표현하는 것은 너무 복잡할 것 같네요.
edge 정보는 가져오지 않도록 수정할게요

2024-11-13 02:14 UTC, ezcolin2 commented on backend/src/node/node.service.ts
> +        'outgoingEdges.id',
다시 살펴보니 중첩 쿼리로 select를 지정할 수가 있네요 그렇게 수정해보겠습니다!
```ts
    const node = await this.nodeRepository.findOne({
      relations: ['page'],
      select: {
        id: true,
        page: {
          id: true,
          title: true, // content 제외하고 title만 선택
        },
      },
      where: {
        id,
      },
    });
```

2024-11-13 02:36 UTC, Tolerblanc approved these changes
LGTM 👍

2024-11-13 02:36 UTC, merged