변경 사항만 데이터베이스에 반영
boostcampwm-2024/web15-OctoDocs pull request #280
Opened 2024-11-25 14:53 UTC by ezcolin2

## 🔖 연관된 이슈

- #276 

## 📂 작업 내용

## 변경 사항만 데이터베이스에 반영

기존 코드는 node 하나만 변경되더라도 모든 노드의 정보를 검사 후 데이터베이스에 반영됩니다.

즉, 변경되지 않은 노드도 함께 검사하는 이슈가 있었습니다.

```ts
      // node의 변경 사항을 감지한다.
      nodesMap.observe(async () => {
        const nodes = Object.values(doc.getMap('nodes').toJSON());

        // 모든 노드에 대해 검사한다.
        for await (const node of nodes) {
          const { title, id } = node.data; // TODO: 이모지 추가
          const { x, y } = node.position;
          const isHolding = node.isHolding;
          const updateCondition =
            !(await this.nodeCacheService.has(id)) ||
            !(await this.nodeCacheService.hasSameTitle(id, title)) ||
            !(await this.nodeCacheService.isHoldingStatusChanged(
              id,
              isHolding,
            ));

          if (updateCondition) {
            await this.nodeService.updateNode(id, { title, x, y });
            await this.nodeCacheService.set(id, { title, isHolding });
          }
        }
      });
```

YMap이 제공해주는 observe 메소드는 내부에서 변경된 key 값만 감지한 후 해당 value만 가져올 수 있습니다.

```ts
      // node의 변경 사항을 감지한다.
      nodesMap.observe(async (event) => {
        for (const [key, change] of event.changes.keys) {
          if (change.action === 'update') {
            const node: any = nodesMap.get(key);
            const { title, id } = node.data; // TODO: 이모지 추가
            const { x, y } = node.position;
            const isHolding = node.isHolding;
            if (!isHolding) {
              await this.nodeService.updateNode(id, { title, x, y });
            }
          }
        }
      });
```

## node-cache 삭제

기존에는 title과 노드의 위치가 변경되면 모두 nodeMap에서 변경 사항이 감지되었습니다.

이제 title을 분리하여 title이 변경되면 title만, 노드가 변경되면 노드만 변경 사항을 감지할 수 있습니다.

```ts
      title.observeDeep(async (event) => {
        // path가 존재할 때만 페이지 갱신
        event[0].path.toString().split('_')[1] &&
          this.pageService.updatePage(
            parseInt(event[0].path.toString().split('_')[1]),
            {
              title: event[0].target.toString(),
            },
          );
      });
```

## page update api 변경

title, content, emoji 중 일부만 들어와도 변경할 수 있도록 수정했습니다.

## title과 emoji 초기 세팅

기존에는 node의 title과 emoji 값만 세팅해주었습니다.

하지만 노드 안의 page에서 title과 emoji는 별도의 YMap으로 관리하기 때문에 페이지 안의 title, emoji 값이 변경되지 않는 이슈가 있었습니다.

title과 emoji는 node에서 얻을 수 있었기 때문에 initializeYNodeMap 함수에서 함께 세팅해주도록 구현했습니다.

```ts
  // YMap에 노드 정보를 넣어준다.
  initializeYNodeMap(nodes: Node[], yMap: Y.Map<unknown>): void {
    nodes.forEach((node) => {
      const nodeId = node.id.toString(); // id를 string으로 변환

      // Y.Map에 데이터를 삽입
      yMap.set(nodeId, {
        id: nodeId,
        type: 'note',
        data: {
          title: node.page.title,
          id: node.page.id,
          emoji: node.page.emoji,
        },
        position: {
          x: node.x,
          y: node.y,
        },
        selected: false, // 기본적으로 선택되지 않음
        dragging: true,
        isHolding: false,
      });

      // Y.Text title에 데이터 삽입
      const pageId = node.page.id.toString(); // id를 string으로 변환
      const yTitleText = new Y.Text();
      yTitleText.insert(0, node.page.title);
      // Y.Map에 데이터를 삽입
      yMap.set(`title_${pageId}`, yTitleText);

      // Y.Text emoji에 데이터 삽입
      const yEmojiText = new Y.Text();
      const emoji = node.page.emoji ?? '📄';
      console.log(node.page);
      yEmojiText.insert(0, emoji);
      // Y.Map에 데이터를 삽입
      yMap.set(`emoji_${pageId}`, yEmojiText);
    });
  }

```

## 프론트 title 업데이트 코드 제거

title과 emoji가 변경되면 서버에 update query를 날리는 코드가 있었는데 일단 주석처리를 해두었습니다.

그래서 지금은 page title이 바뀌면 노드의 title이 실시간으로 바뀌지 않습니다.

한 번 코드를 손대보려고 했는데 처음 보는 코드가 많아서 일단 주석처리 해두었습니다.

2024-11-25 17:02 UTC, yewonJin commented
프론트엔드 쪽 update query 코드 다 삭제했습니다!
그리고 에디터 제목이나 이모지가 변경되면 페이지 리스트와 노드에 반영되게 했습니다!

근데 조금씩 에러 있는 거 같아서 나중에 다시 손봐야할 것 같네용

2024-11-25 22:21 UTC, Tolerblanc requested changes
성민님 수고 많으셨습니다! 몇 가지 의견 남겨놨는데, 확인 부탁드려요.

2024-11-25 22:21 UTC, Tolerblanc commented on apps/backend/src/page/page.service.ts
> +    if (dto.title !== undefined) {
P2: `const newPage = Object.assign({}, page, dto)` 로 확 줄일 수 있을 것 같습니다!

2024-11-25 22:21 UTC, Tolerblanc commented on apps/backend/src/yjs/yjs.service.ts
> +        // 페이지 내용 변경 사항을 감지해서 데이터베이스에 갱신합니다.
👍 👍

2024-11-25 22:21 UTC, Tolerblanc commented on apps/backend/src/yjs/yjs.service.ts
> +          }
P2: 이것도 그렇고, 밑에 `edge`도 그렇고, `for - of` 에서 하나씩 찾아서 서비스 찍을 때 마다 쿼리가 한 줄씩 날라가는 형태인데, 아예 여기서 `bulkUpdate` 를 적용하는 건 어떠신가요? `for - of` 안에서는 `id: {title, x, y}` 만 쌓아두다가, 서비스 내부에서 여러 노드를 한 번에 업데이트 할 수 있는 메서드 (= 여러 노드를 쿼리 한 줄로 업데이트 할 수 있는 메서드) 를 호출하면 더 최적화 할 수 있지 않을까 생각이 듭니다!

2024-11-26 00:47 UTC, ezcolin2 commented on apps/backend/src/page/page.service.ts
> +    if (dto.title !== undefined) {
오 좋은 방법이네요! 적용하겠습니다

2024-11-26 00:54 UTC, ezcolin2 commented on apps/backend/src/yjs/yjs.service.ts
> +          }
제가 몇 번 테스트 해봤는데 event.changes.keys가 여러 개 나오는 경우는 안 보이더라고요.
그래도 혹시 모를 상황에 대비해서 bulk update 구현해두겠습니다!

2024-11-26 02:35 UTC, ezcolin2 commented on apps/backend/src/yjs/yjs.service.ts
> +          }
그런데 제가 계속 고민해보았는데 저희가 노드, title, emoji, node 전부 분리해두어서 사실상 event.changes.keys가 2개 이상 나올 가능성은 정말 특수한 상황이 아닌 이상 거의 없을 것 같습니다.
지금 시점에서 bulk update를 적용하는 것은 뭔가 오버 엔지니어링이라는 생각이 드는데 어떻게 생각하시나요?

2024-11-26 02:37 UTC, Tolerblanc commented on apps/backend/src/yjs/yjs.service.ts
> +          }
그렇다면 굳이 적용할 필요는 없어보이네요. `page.service.ts` 만 수정해주시면 바로 approve 하겠습니다!

2024-11-26 02:43 UTC, ezcolin2 commented on apps/backend/src/yjs/yjs.service.ts
> +          }
넵 몇 가지 더 수정해서 올렸습니다!

2024-11-26 02:46 UTC, Tolerblanc approved these changes

2024-11-26 02:46 UTC, merged