user, workspace 관련 api 구현
boostcampwm-2024/web15-OctoDocs pull request #293
Opened 2024-11-26 10:18 UTC by summersummerwhy

## 🔖 연관된 이슈

- closes #

## 📂 작업 내용

-

## 📑 참고 자료 & 스크린샷 (선택)

## 📢 리뷰 요구사항 (선택)

2024-11-26 10:27 UTC, ezcolin2 commented
localhost key는 .gitignore에 등록하면 어떨까요?

2024-11-26 10:57 UTC, Tolerblanc commented
.gitignore에 `.crt` 랑 `.key` 넣어놨던 것 같은데 왜 들어 갔을까요...ㅠ

2024-11-27 04:26 UTC, ezcolin2 commented on apps/backend/src/auth/token/token.service.ts
> +    }
에러를 잡아서 Error로 던져주고 있는데 그냥 어차피 jwtService에서 Error를 던져주니까  try, catch 없애도 괜찮을 것 같습니다.

2024-11-27 04:42 UTC, Tolerblanc requested changes
서진님 고생하셨습니다!!
삭제할 파일이 있어서 Request changes 달았습니다

2024-11-27 04:42 UTC, Tolerblanc commented on .gitignore
> +services/nginx/ssl/localhost.crt
요거 301번 PR에서 `*.crt` 와 `*.key`로 수정했습니다. 지워도 될 듯 합니다!

2024-11-27 04:42 UTC, Tolerblanc commented on .vscode/settings.json
> +}
요것도 지워주세요...!

2024-11-27 04:42 UTC, Tolerblanc commented on apps/backend/src/auth/token/token.service.ts
> +    }
저도 동의합니다

2024-11-27 04:42 UTC, Tolerblanc commented on apps/backend/src/auth/token/token.service.ts
> +      sameSite: 'strict',
요거 혹시 실 테스트 해보셨나요?? 

(메모용) `.clearCookie`가 안먹었던 적이 있었는데, 혹시나 해보고 안되면, `.cookie`로 `expires` 한참 전으로 설정하면 될 겁니다

2024-11-27 04:42 UTC, Tolerblanc commented on apps/backend/src/auth/guards/jwt-auth.guard.ts
명확하게 읽기 좋긴 한데, 인덴트가 많이 들어가는 건 어쩔 수 없군요 ㅜ 
다른 곳이 지저분해지는 것 보다 가드만 이렇게 되는게 더 나은 것 같기도 하고...

2024-11-27 05:25 UTC, summersummerwhy commented on apps/backend/src/auth/token/token.service.ts
> +      sameSite: 'strict',
테스트 해보겠습니다!!

2024-11-27 05:46 UTC, yewonJin commented on apps/backend/src/auth/token/token.service.ts
> +      sameSite: 'strict',
일단 프론트 로컬 환경에서는 다 정상적으로 동작했습니다

2024-11-27 05:59 UTC, summersummerwhy commented on apps/backend/src/auth/guards/jwt-auth.guard.ts
ㅠㅜㅜ 맞아요 refresh 로직도 따로 떼서 리팩토링해야될것같은데... 일단 다른 기능까지 끝내보고 만져야겠어요

2024-11-27 06:16 UTC, Tolerblanc approved these changes

2024-11-27 06:16 UTC, merged